apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistent.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistent.storageClassName }}
  resources:
    requests:
      storage: 128Mi
