apiVersion: v1
kind: Service
metadata:
  name: solitair-deploy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: solitair
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solitair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solitair
  template:
    metadata:
      labels:
        app: solitair
    spec:
      containers:
        - name: solitair
          image: chimenesjr/solitaire:nginx