apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistent.name }}
spec:
  storageClassName: {{ .Values.persistent.storageClassName }}
  capacity:
    storage: {{ .Values.persistent.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
