apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistent.name }}
spec:
  storageClassName: {{ .Values.persistent.storageClassName }}
  accessModes: # Once = one node
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistent.storage }}
