name: "web-app"
image:
  repository: eranzaksh/infinity
  tag: "353fd1f"
service:
  type: ClusterIP
  port: 5000
spec:
  replicaCount: 2
volumes:
  name: caching
  mountPath: /home/cache
persistent:
  name: caching-pv
  storage: 128Mi
  storageClassName: manual
ingress:
  spec:
    host: eran.humi.com
secret:
  key: "default"
