name: "web-app"
image:
  repository: eranzaksh/infinity
  tag: "52-e85e55d4389d33eaeeef1dab52e6a47acd481b82"
service:
  type: ClusterIP
  port: 5001
spec:
  replicaCount: 1
volumes:
  name: caching
  mountPath: cache
persistent:
  name: caching-pv
  storage: 1Gi
  storageClassName: ebs-gp3
ingress:
  spec:
    host:
secret:
  key: "default"
configmap:
  bgColor: "#FFA07A"
