name: "web-app"
image:
  repository: eranzaksh/infinity
  tag: "00c635d"
service:
  type: ClusterIP
  port: 5001
spec:
  replicaCount: 2
volumes:
  name: caching
  mountPath: /home/cache
persistent:
  name: caching-pv
  storage: 128Mi
  storageClassName: ebs-gp3
ingress:
  spec:
    host: 
secret:
  key: "default"
