name: "web-app"
image:
  repository: eranzaksh/infinity
  tag: "50-f6da8b2ff2c3527cc5da1935c1f99bbd456a7ad4"
service:
  type: ClusterIP
  port: 5001
spec:
  replicaCount: 1
volumes:
  name: caching
  mountPath: /home/cache
persistent:
  name: caching-pv
  storage: 1Gi
  storageClassName: ebs-gp3
ingress:
  spec:
    host:
secret:
  key: "default"
configmap:
  bgColor: "#FFA07A"
