name: "web-app"
image:
  repository: eranzaksh/infinity
  tag: "54-905665f8cf9907d9d29f6ae57dfbb84af48bde90"
service:
  type: ClusterIP
  port: 5001
spec:
  replicaCount: 1
volumes:
  name: caching
  mountPath: /cache
persistent:
  name: caching-pv
  storage: 1Gi
  storageClassName: ebs-gp3
ingress:
  spec:
    host:
secret:
  key: "default"
configmap:
  bgColor: "#FFA07A"
