name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to use'
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
  
      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/download/v4.27.3/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
  
      - name: Update image tag in values.yaml
        run: |
          yq eval ".image.tag = \"${{ github.event.inputs.commit_hash }}\"" -i ./weather-helm/eran-app2/values.yaml 
  
      - name: Commit updated values.yaml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./weather-helm
          git commit -m "Update image tag to ${{ github.event.inputs.commit_hash }}"
      
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}  # Push to the current branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
